#! /bin/bash
clear
echo " "
echo " ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo " " 
echo " Verificando todo ambiente de execução da aplicação GO..."
echo " " 
echo " Verificando os conteineres..."
echo " "
echo "---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
sudo docker ps -a | grep f2-modulo1-curso2-projeto-go-testes
echo "----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo " "
echo " Verificando as imagens dos conteineres PostgreSQL e PGAdmin. "
echo " " 
echo "---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo "Imagem do conteiner do PostgreSQL: "
sudo docker images | grep postgres
echo "---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo "Imagem do conteiner do PGAdmin: "
sudo docker images | grep  dpage/pgadmin4
echo "---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo " "
echo " Verificando se a aplicação está rodando..."
echo " "
echo " Identificação do processo em execução da aplicação  main.go..."
echo " " 
echo " [ "$( ps aux | grep main.go | grep -v grep | head -n 1 | awk '{print $2}')" ] "
echo " "
echo " Identificação do processo em execução na porta 8080."
echo " "
echo " [ "$(lsof -i :8080 | grep -v PID | head -n 2 | awk '{print $2}')" ] "
echo " "
echo " --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo " "
echo "Para rodar a aplicação novamente juntamente com toda infra estrutura tente as opções abaixo:"
echo " " 
echo " 1 - No terminal 1, para dar um start em todos os recursos, banco + aplicação: (somente se os conteineres e as imagens ainda existirem, caso contrário rodar a outra opção ./criar-ambiente.sh)"
echo " "
echo "   ./start-ambiente.sh"
echo " "
echo " 2 - No terminal 1 , para recriar completamente o ambiente Banco de Dados + Aplicação, então execute o script abaixo e siga todas as orientações informadas por ele: "
echo " "
echo "   ./criar-ambiente.sh "
echo " "
echo " --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo " "
echo " Depois volte no terminal 4 e execute novamente: "
echo " " 
echo "   ./ver-ambiente.sh "
echo " "
echo " --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo " "
echo " Caso queira testar os ambientes no browser:"
echo " "
echo " Apicação rodando:"
echo " " 
echo "    http://0.0.0.0:8080/Bruno"
echo " "
echo " PGAdmin: "
echo " " 
echo "     http://0.0.0.0:54321"
echo " " 
echo "    Login e-mail: gui@alura.com "
echo " " 
echo "    Senha       : 123456   <--- melhor digitar que copiar, porque algums espaço pode ir junto e acabar gerando erro de senha.  "
echo " " 
echo " --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo " "
echo " OBS: se a conexão com o banco não estiver funcionando, considere consultar novamente o IP do conteiner PostgreSQL."
echo " " 
echo "     sudo docker inspect f2-modulo1-curso2-projeto-go-testes-postgres-1 | grep IPAddress"
echo " " 
echo " Copie esse IP, no PGADmin, no server, clique com o botão direito e selecione properties, então na aba Connections do Banco de dadodos, altere o IP no campo Address."
echo " "
echo " Passo a passo de sexmplo para configurar um novo server no PGadmin:"
echo " -------------------------------------------------------------------"
echo " 1 - Add New Server "
echo " 2 - [Aba General] Nme: Meu servidor"
echo " 3 - [Aba Connection] Host name / address: <COLOQUE AQUI O IO DO CONTEINER POSTGRESQL>" 
echo " 4 - [Aba Connection] Port               : 5432  "
echo " 5 - [Aba Connection] Database           : root "
echo " 6 - [Aba Cpmmecton] Username            : root "
echo " 7 - [aba Connection] Password           : root " 
echo " ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"
echo " "
