# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:

  setup-docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Update apt cache
        run: sudo apt update
      - name: Install Docker Engine
        run: sudo apt install docker-ce
      - name: Add Docker to non-root users
        run: sudo usermod -aG docker $USER
      - name: Install Docker Compose
        run: sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
      - name: Adjust permission
        run: sudo chmod +x /usr/local/bin/docker-compose
      - name: Test Docker installation
        run: docker run hello-world

  test:
    needs: setup-docker
    runs-on: ${{ matrix.so_linux_ubuntu_version }}
    strategy:
      matrix:
#        so_linux_ubuntu_version: ['ubuntu-21.10', 'ubuntu-22.04', '>=ubuntu-23.04']
#        so_linux_ubuntu_version: ['ubuntu-21.10', '>=ubuntu-23.04', 'windows-11']
        so_linux_ubuntu_version: ['ubuntu-22.04']        
#        go_version: ['1.18', '1.17', '>=1.18']
        go_version: ['1.17']
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build-Database
      run: docker-compose build

    - name: Run-Database
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go
  
  build:
    needs: test
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go