# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:

  setup-docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Update apt cache
        run: sudo apt update
      - name: Install packages
        run: sudo apt install -y ca-certificates curl gnupg lsb-release
      - name: Add Docker repository
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg   

          echo "deb [arch=$(dpkg --architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list

      - name: Update apt cache
        run: sudo apt update
      - name: Install Docker Engine
        run: sudo apt install docker-ce
      - name: Start Docker service
        run: sudo systemctl start docker
      - name: Verify Docker installation
        run: docker run hello-world

  test:
    needs: setup-docker
    runs-on: ${{ matrix.so_linux_ubuntu_version }}
    strategy:
      matrix:
#        so_linux_ubuntu_version: ['ubuntu-21.10', 'ubuntu-22.04', '>=ubuntu-23.04']
#        so_linux_ubuntu_version: ['ubuntu-21.10', '>=ubuntu-23.04', 'windows-11']
        so_linux_ubuntu_version: ['ubuntu-22.04']        
#        go_version: ['1.18', '1.17', '>=1.18']
        go_version: ['1.17']
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build-Database
      run: docker-compose build

    - name: Run-Database
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go
  
  build:
    needs: test
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go