
name: CI Projeto GO Testes

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg POSTGRES_USER=root \
            --build-arg POSTGRES_PASSWORD=root \
            --build-arg POSTGRES_DB=root \
            -t my-postgres:latest .

      - name: Run container
        run: |
          docker run \
            -d \
            -p 5432:5432 \
            -v postgres-data:/var/lib/postgresql/data \
            my-postgres:latest

      - name: Run container
        run: |
          docker run \
            -d \
            -p 54321:80 \
            -v postgres-data:/var/lib/postgresql/data \
            dpage/pgadmin4:latest            

      - name: Test
        run: go test -v main_test.go
