
name: Build Conteiners abd Run

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run container
        run: |
          docker run \
            -d \
            -p 5432:5432 \
            -v postgres-data:/var/lib/postgresql/data \
            postgres:latest

      - name: Run container
        run: |
          docker run \
            -d \
            -p 54321:80 \
            -v postgres-data:/var/lib/postgresql/data \
            dpage/pgadmin4:latest            
            
      - name: Test
        run: go test -v main_test.go