
name: CI Projeto GO Testes

# V2 - versão com separação em 2 jobs
# job 1 - Build da imagem que será usada na construção dos conteiners. Enviar essa imagem para o registry do DockerHub
# job 2 - Logar no docker hub, baixar a imagem, rodar conteineres e testar a aplicação

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_containers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg POSTGRES_USER=root \
            --build-arg POSTGRES_PASSWORD=root \
            --build-arg POSTGRES_DB=root \
            -t brunojose1977/my-postgres:latest . 
          
      - name: Push image to Docker Hub Registry
        run: docker push brunojose1977/my-postgres:latest          
           
  run_containers_and_test:
    runs-on: ubuntu-latest
    needs: build_containers
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image my-postgres from Docker Hub
        run: docker pull brunojose1977/my-postgres:latest          

      - name: Run Container PostgreSQL 
        run: |
          docker run \
            -d \
            -p 5432:5432 \
            -v postgres-data:/var/lib/postgresql/data \
            brunojose1977/my-postgres:latest

      - name: Run Container PGAdmin
        run: |
          docker run \
            -d \
            -p 54321:80 \
            dpage/pgadmin4:latest            

      - name: Test
        run: go test -v main_test.go

      
      # Problema detectado e em correção:
      # - Não é possível conectar ao banco criado por conteiner no outro job;
      # - Se eu tentar rodar o Conteiner aqui vai dar erro na imagem porque a imagem criada localmente não está visível a esse job;
      # - Não posso usar a imagem my-postgres da minha conta DockerHub, porque não sei tratar as credenciais de acesso da minha conta dentro do Job
      #  provavelente eu vou ter que configurar um secrets dentro do Github pra fazer um "docker login" e depois um "docker push";
