
name: CI Projeto GO Testes

# V5 - versão com separação em 2 jobs - simples com apenas 1 versão da linguagem GO e apenas 1 SO
# job 1 - Build da imagem que será usada na construção dos conteiners. Enviar essa imagem para o registry do DockerHub
# job 2 - Logar no docker hub, baixar a imagem, rodar conteineres e testar a aplicação
#       - Matrix Strategy for Go versions

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_containers:
    runs-on: ${{ matrix.so_type_version }}
    strategy:
      matrix:
        go_version: ['1.17',]
        so_type_version: ['ubuntu-latest']
        # Versões do ubunto que o runner para e fica em espera: 19.10, 21.10, 22.10, 23.10
        # rodam de boa! 20.04, 22.04
    steps:
      - uses: actions/checkout@v3
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
            sudo apt-get update
            sudo apt-get install docker-compose         

      - name: docker-compose build
        run: |
          docker-compose build 
#          docker-compose build \
#            --build-arg POSTGRES_USER=root \
#            --build-arg POSTGRES_PASSWORD=root \
#            --build-arg POSTGRES_DB=root .
#            -t brunojose1977/my-postgres:latest . 
          
#      - name: Push image to Docker Hub Registry
#        run: docker push brunojose1977/my-postgres:latest          
           
  run_containers_and_test:
    runs-on: ${{ matrix.so_type_version }}
    needs: build_containers
    strategy:
        matrix:
          go_version: ['1.17',]
          so_type_version: ['ubuntu-latest']          
    steps:
      - uses: actions/checkout@v3
      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Pull image my-postgres from Docker Hub
#        run: docker pull brunojose1977/my-postgres:latest          
  

      - name: docker compose up 
        run: docker compose up -d

      - name: Test
        run: go test -v main_test.go
