name: Go CI IA Gemmini

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest, ubuntu-22.04'] 
        go: ['1.17', '1.18']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      run: go test -v main_test.go 
    - name: Build
      run: go build -v main.go