
name: CI Projeto GO Testes

# V2 - versão com separação em 2 jobs
# job 1 - build and run containers
# job 2 - test application

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_and_run_containers:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build \
            --build-arg POSTGRES_USER=root \
            --build-arg POSTGRES_PASSWORD=root \
            --build-arg POSTGRES_DB=root \
            -t my-postgres:latest .

      - name: Run Container PostgreSQL 
        run: |
          docker run \
            -d \
            -p 5432:5432 \
            -v postgres-data:/var/lib/postgresql/data \
            my-postgres:latest

      - name: Run Container PGAdmin
        run: |
          docker run \
            -d \
            -p 54321:80 \
            dpage/pgadmin4:latest            
           
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: go test -v main_test.go